apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.headlessName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: sentinel
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
